"""Geodetic datum table for PMTK330 / PMTK430 (SET/QUERY DATUM).

Transcribed verbatim from Appendix A of the MT3333 Platform NMEA Message
Specification for GPS+GLONASS, V1.00 (2013-09-26) -- see
docs/MT3333_NMEA_Message_Specification_V1.00.pdf.

The body text of that document says "219 different datums"; the appendix
actually enumerates 223, numbered 0-222 with no gaps.  The table below is the
appendix, which is what the chipset indexes against.

Index 3 ("User Setting") selects the user-defined ellipsoid programmed with
PMTK331 (SET_DATUM_ADVANCE).
"""

from __future__ import annotations

#: index -> (datum name, region)
DATUMS: dict[int, tuple[str, str]] = {
    0: ('WGS1984', 'International'),
    1: ('Tokyo', 'Japan'),
    2: ('Tokyo', 'Mean For Japan, South Korea, Okinawa'),
    3: ('User Setting', 'User Setting'),
    4: ('Adindan', 'Burkina Faso'),
    5: ('Adindan', 'Cameroon'),
    6: ('Adindan', 'Ethiopia'),
    7: ('Adindan', 'Mali'),
    8: ('Adindan', 'Mean For Ethiopia, Sudan'),
    9: ('Adindan', 'Senegal'),
    10: ('Adindan', 'Sudan'),
    11: ('Afgooye', 'Somalia'),
    12: ('Ain El Abd1970', 'Bahrain'),
    13: ('Ain El Abd1970', 'Saudi Arabia'),
    14: ('American Samoa1962', 'American Samoa Islands'),
    15: ('Anna 1 Astro1965', 'Cocos Island'),
    16: ('Antigua Island Astro1943', 'Antigua(Leeward Islands)'),
    17: ('Arc1950', 'Botswana'),
    18: ('Arc1950', 'Burundi'),
    19: ('Arc1950', 'Lesotho'),
    20: ('Arc1950', 'Malawi'),
    21: ('Arc1950', 'Mean For Botswana, Lesotho, Malawi, Swaziland, Zaire, Zambia, Zimbabwe'),
    22: ('Arc1950', 'Swaziland'),
    23: ('Arc1950', 'Zaire'),
    24: ('Arc1950', 'Zambia'),
    25: ('Arc1950', 'Zimbabwe'),
    26: ('Arc1960', 'Mean For Kenya Tanzania'),
    27: ('Arc1960', 'Kenya'),
    28: ('Arc1960', 'Tamzamia'),
    29: ('Ascension Island1958', 'Ascension Island'),
    30: ('Astro Beacon E 1945', 'Iwo Jima'),
    31: ('Astro Dos 71/4', 'St Helena Island'),
    32: ('Astro Tern Island (FRIG) 1961', 'Tern Island'),
    33: ('Astronomical Station 1952', 'Marcus Island'),
    34: ('Australian Geodetic 1966', 'Australia, Tasmania'),
    35: ('Australian Geodetic 1984', 'Australia, Tasmania'),
    36: ('Ayabelle Lighthouse', 'Djibouti'),
    37: ('Bellevue (IGN)', 'Efate and Erromango Islands'),
    38: ('Bermuda 1957', 'Bermuda'),
    39: ('Bissau', 'Guuinea-Bissau'),
    40: ('Bogota Observatory', 'Colombia'),
    41: ('Bukit Rimpah', 'Indonesia(Bangka and Belitung Ids)'),
    42: ('Camp Area Astro', 'Antarctica(McMurdi Camp Area)'),
    43: ('Campo Inchauspe', 'Argentina'),
    44: ('Canton Astro1966', 'Phoenix Island'),
    45: ('Cape', 'South Africa'),
    46: ('Cape Canaveral', 'Bahamas, Florida'),
    47: ('Carthage', 'Tunisia'),
    48: ('Chatham Island Astro1971', 'New Zealand(Chatham Island)'),
    49: ('Chua Astro', 'Paraguay'),
    50: ('Corrego Alegre', 'Brazil'),
    51: ('Dabola', 'Guinea'),
    52: ('Deception Island', 'Deception Island, Antarctia'),
    53: ('Djakarta (Batavia)', 'Indonesia(Sumatra)'),
    54: ('Dos 1968', 'New Georgia Islands (Gizo Island)'),
    55: ('Easter Island 1967', 'Easter Island'),
    56: ('Estonia Coordinate System1937', 'Estonia'),
    57: ('European 1950', 'Cyprus'),
    58: ('European 1950', 'Egypt'),
    59: ('European 1950', 'England, Channel Islands, Scotland, Shetland Islands'),
    60: ('European 1950', 'England, Ireland, Scotland, Shetland Islands'),
    61: ('European 1950', 'Finland, Norway'),
    62: ('European 1950', 'Greece'),
    63: ('European 1950', 'Iran'),
    64: ('European 1950', 'Italy (Sardinia)'),
    65: ('European 1950', 'Italy (Slcily)'),
    66: ('European 1950', 'Malta'),
    67: ('European 1950', 'Mean For Austria, Belgium,Denmark, Finland, France, W Germany, Gibraltar, Greece, Italy, Luxembourg, Netherlands, Norway, Portuga,l Spain, Sweden, Switzerland'),
    68: ('European 1950', 'Mean For Austria, Debnmark,France, W Germany, Netherland , Switzerland'),
    69: ('European 1950', 'Mean For Irag, Israel, Jordan, Lebanon, Kuwait, Saudi Arabia, Syria'),
    70: ('European 1950', 'Portugal, Spain'),
    71: ('European 1950', 'Tunisia,'),
    72: ('European 1979', 'Mean For Austria, Finland ,Netherlands ,Norway, Spain, Sweden, Switzerland'),
    73: ('Fort Thomas 1955', 'Nevis St Kitts (Leeward Islands)'),
    74: ('Gan 1970', 'Republic Of Maldives'),
    75: ('Geodetic Dataum 1970', 'New Zealand'),
    76: ('Graciosa Base SW1948', 'Azores (Faial, Graciosa, Pico, Sao, Jorge, Terceria)'),
    77: ('Guam1963', 'Guam'),
    78: ('Gunung Segara', 'Indonesia (Kalimantan)'),
    79: ('Gux l Astro', 'Guadalcanal Island'),
    80: ('Herat North', 'Afghanistan'),
    81: ('Hermannskogel Datum', 'Croatia-Serbia, Bosnia-Herzegoivna'),
    82: ('Hjorsey 1955', 'Iceland'),
    83: ('Hongkong 1963', 'Hongkong'),
    84: ('Hu Tzu Shan', 'Taiwan'),
    85: ('Indian', 'Bangladesh'),
    86: ('Indian', 'India,Nepal'),
    87: ('Indian', 'Pakistan'),
    88: ('Indian 1954', 'Thailand'),
    89: ('Indian 1960', 'Vietnam (Con Son Island)'),
    90: ('Indian 1960', 'Vietnam (Near 16 deg N)'),
    91: ('Indian 1975', 'Thailand'),
    92: ('Indonesian 1974', 'Indonesian'),
    93: ('Ireland 1965', 'Ireland'),
    94: ('ISTS 061 Astro 1968', 'South Georgia Islands'),
    95: ('ISTS 073 Astro 1969', 'Diego Garcia'),
    96: ('Johnston Island 1961', 'Johnston Island'),
    97: ('Kandawala', 'Sri Lanka'),
    98: ('Kerguelen Island 1949', 'Kerguelen Island'),
    99: ('Kertau 1948', 'West Malaysia and Singapore'),
    100: ('Kusaie Astro 1951', 'Caroline Islands'),
    101: ('Korean Geodetic System', 'South Korea'),
    102: ('LC5 Astro 1961', 'Cayman Brac Island'),
    103: ('Leigon', 'Ghana'),
    104: ('Liberia 1964', 'Liberia'),
    105: ('Luzon', 'Philippines (Excluding Mindanao)'),
    106: ('Luzon', 'Philippines (Mindanao)'),
    107: ("M'Poraloko", 'Gabon'),
    108: ('Mahe 1971', 'Mahe Island'),
    109: ('Massawa', 'Ethiopia (Eritrea)'),
    110: ('Merchich', 'Morocco'),
    111: ('Midway Astro 1961', 'Midway Islands'),
    112: ('Minna', 'Cameroon'),
    113: ('Minna', 'Nigeria'),
    114: ('Montserrat Island Astro 1958', 'Montserrat (Leeward Island)'),
    115: ('Nahrwan', 'Oman (Masirah Island)'),
    116: ('Nahrwan', 'Saudi Arabia'),
    117: ('Nahrwan', 'United Arab Emirates'),
    118: ('Naparima BWI', 'Trinidad and Tobago'),
    119: ('North American 1927', 'Alaska (Excluding Aleutian Ids)'),
    120: ('North American 1927', 'Alaska (Aleutian Ids East of 180 degW)'),
    121: ('North American 1927', 'Alaska (Aleutian Ids West of 180 degW)'),
    122: ('North American 1927', 'Bahamas (Except San Salvador Islands)'),
    123: ('North American 1927', 'Bahamas (San Salvador Islands)'),
    124: ('North American 1927', 'Canada (Alberta, British Columbia)'),
    125: ('North American 1927', 'Canada (Manitoba, Ontario)'),
    126: ('North American 1927', 'Canada (New Brunswick, Newfoundland, Nova Scotia, Qubec)'),
    127: ('North American 1927', 'Canada (Northwest Territories, Saskatchewan)'),
    128: ('North American 1927', 'Canada (Yukon)'),
    129: ('North American 1927', 'Canal Zone'),
    130: ('North American 1927', 'Cuba'),
    131: ('North American 1927', 'Greenland (Hayes Peninsula)'),
    132: ('North American 1927', 'Mean For Antigua, Barbados, Barbuda, Caicos Islands, Cuba, Dominican, Grand Cayman, Jamaica, Turks Islands'),
    133: ('North American 1927', 'Mean For Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua'),
    134: ('North American 1927', 'Mean For Canada'),
    135: ('North American 1927', 'Mean For Conus'),
    136: ('North American 1927', 'Mean For Conus (East of Mississippi, River Including Louisiana, Missouri, Minnesota)'),
    137: ('North American 1927', 'Mean For Conus (West of Mississippi, Rive Excluding Louisiana, Minnesota, Missouri)'),
    138: ('North American 1927', 'Mexico'),
    139: ('North American 1983', 'Alaska (Excluding Aleutian Ids)'),
    140: ('North American 1983', 'Aleutian Ids'),
    141: ('North American 1983', 'Canada'),
    142: ('North American 1983', 'Conus'),
    143: ('North American 1983', 'Hahawii'),
    144: ('North American 1983', 'Mexico, Central America'),
    145: ('North Sahara 1959', 'Algeria'),
    146: ('Observatorio Meteorologico 1939', 'Azores (Corvo and Flores Islands)'),
    147: ('Old Egyptian 1907', 'Egypt'),
    148: ('Old Hawaiian', 'Hawaii'),
    149: ('Old Hawaiian', 'Kauai'),
    150: ('Old Hawaiian', 'Maui'),
    151: ('Old Hawaiian', 'Mean For Hawaii, Kauai, Maui, Oahu'),
    152: ('Old Hawaiian', 'Oahu'),
    153: ('Oman', 'Oman'),
    154: ('Ordnance Survey Great Britian 1936', 'England'),
    155: ('Ordnance Survey Great Britian 1936', 'England, Isle of Man, Wales'),
    156: ('Ordnance Survey Great Britian 1936', 'Mean For England ,Isle of Man, Scotland, Shetland Island, Wales'),
    157: ('Ordnance Survey Great Britian 1936', 'Scotland, Shetland Islands'),
    158: ('Ordnance Survey Great Britian 1936', 'Wales'),
    159: ('Pico de las Nieves', 'Canary Islands'),
    160: ('Pitcairn Astro 1967', 'Pitcairn Island'),
    161: ('Point 58', 'Mean For Burkina Faso and Niger'),
    162: ('Pointe Noire 1948', 'Congo'),
    163: ('Porto Santo 1936', 'Porto Santo, Maderia Islands'),
    164: ('Provisional South American 1956', 'Bolovia'),
    165: ('Provisional South American 1956', 'Chile (Northern Near 19 deg S)'),
    166: ('Provisional South American 1956', 'Chile (Southern Near 43 deg S)'),
    167: ('Provisional South American 1956', 'Colombia'),
    168: ('Provisional South American 1956', 'Ecuador'),
    169: ('Provisional South American 1956', 'Guyana'),
    170: ('Provisional South American 1956', 'Mean For Bolivia Chile,Colombia, Ecuador, Guyana, Peru, Venezuela'),
    171: ('Provisional South American 1956', 'Peru'),
    172: ('Provisional South American 1956', 'Venezuela'),
    173: ('Provisional South Chilean 1963', 'Chile (Near 53 deg S) (Hito XVIII)'),
    174: ('Puerto Rico', 'Puerto Rico, Virgin Islands'),
    175: ('Pulkovo 1942', 'Russia'),
    176: ('Qatar National', 'Qatar'),
    177: ('Qornoq', 'Greenland (South)'),
    178: ('Reunion', 'Mascarene Island'),
    179: ('Rome 1940', 'Italy (Sardinia)'),
    180: ('S-42 (Pulkovo 1942)', 'Hungary'),
    181: ('S-42 (Pulkovo 1942)', 'Poland'),
    182: ('S-42 (Pulkovo 1942)', 'Czechoslavakia'),
    183: ('S-42 (Pulkovo 1942)', 'Lativa'),
    184: ('S-42 (Pulkovo 1942)', 'Kazakhstan'),
    185: ('S-42 (Pulkovo 1942)', 'Albania'),
    186: ('S-42 (Pulkovo 1942)', 'Romania'),
    187: ('S-JTSK', 'Czechoslavakia (Prior 1 Jan1993)'),
    188: ('Santo (Dos) 1965', 'Espirito Santo Island'),
    189: ('Sao Braz', 'Azores (Sao Miguel, Santa Maria Ids)'),
    190: ('Sapper Hill 1943', 'East Falkland Island'),
    191: ('Schwarzeck', 'Namibia'),
    192: ('Selvagem Grande 1938', 'Salvage Islands'),
    193: ('Sierra Leone 1960', 'Sierra Leone'),
    194: ('South American 1969', 'Argentina'),
    195: ('South American 1969', 'Bolivia'),
    196: ('South American 1969', 'Brazial'),
    197: ('South American 1969', 'Chile'),
    198: ('South American 1969', 'Colombia'),
    199: ('South American 1969', 'Ecuador'),
    200: ('South American 1969', 'Ecuador (Baltra, Galapagos)'),
    201: ('South American 1969', 'Guyana'),
    202: ('South American 1969', 'Mean For Argentina, Bolivia, Brazil,Chile, Colombia, Ecuador, Guyana, Paraguay, Peru, Trinidad and Tobago, Venezuela'),
    203: ('South American 1969', 'Paraguay'),
    204: ('South American 1969', 'Peru'),
    205: ('South American 1969', 'Trinidad and Tobago'),
    206: ('South American 1969', 'Venezuela'),
    207: ('South Asia', 'Singapore'),
    208: ('Tananarive Observatory 1925', 'Madagascar'),
    209: ('Timbalai 1948', 'Brunei, E Malaysia (Sabah Sarawak)'),
    210: ('Tokyo', 'Japan'),
    211: ('Tokyo', 'Mean For Japan, South Korea, Okinawa'),
    212: ('Tokyo', 'Okinawa'),
    213: ('Tokyo', 'South Korea'),
    214: ('Tristan Astro 1968', 'Tristam Da Cunha'),
    215: ('Viti Levu 1916', 'Fiji (Viti Levu Island)'),
    216: ('Voirol 1960', 'Algeria'),
    217: ('Wake Island Astro 1952', 'Wake Atoll'),
    218: ('Wake-Eniwetok 1960', 'Marshall Islands'),
    219: ('WGS 1972', 'Global Definition'),
    220: ('WGS 1984', 'Global Definition'),
    221: ('Yacare', 'Uruguay'),
    222: ('Zanderij', 'Suriname'),
}

USER_DATUM_INDEX = 3
WGS84_INDEX = 0


def datum_label(index: int) -> str:
    """Human-readable "N - Name (Region)" label, or a placeholder if unknown."""
    try:
        name, region = DATUMS[index]
    except KeyError:
        return f"{index} - (unknown datum)"
    return f"{index} - {name} ({region})"
