"""image_patcher.py - takes an already-built OpenMANET factory
.img.gz (produced by the normal firmware build - this tool does NOT
run the OpenWrt build system) and bakes a node's config into it by
loop-mounting the root partition, writing the generated UCI files plus
a uci-defaults script that installs them at first boot, and re-gzipping.

This mirrors exactly what was done by hand during interactive testing
this session (mount -o rw, edit /etc/config/*, unmount) - just
automated and repeatable per node, and using a late-numbered
uci-defaults script (see UCI_DEFAULTS_NAME) rather than editing
/etc/config/* directly, so the same base image can be re-patched for a
different node without needing to track what the *previous* patch
changed.

Linux only (loop devices, mount). Requires root.
"""
import gzip
import os
import shutil
import subprocess
import tempfile

UCI_DEFAULTS_NAME = "99z_preconfig"
TEMPLATE_DIR = "/usr/share/openmanet-node-builder-preconfig"

UCI_DEFAULTS_SCRIPT = f"""#!/bin/sh
# Generated by openmanet-node-builder - overwrites the wizard-produced
# defaults with this node's pre-baked config snapshot. Runs after all
# packages are installed and after every other first-boot script, so
# this deterministically wins regardless of what earlier scripts set.

SRC={TEMPLATE_DIR}

for f in network wireless dhcp firewall mesh11sd system; do
\tcp "$SRC/$f" "/etc/config/$f"
done

mkdir -p /etc/openmanetd
cp "$SRC/openmanetd-config.yml" /etc/openmanetd/config.yml

echo 'root:__ADMIN_PASSWORD__' | chpasswd >/dev/null 2>&1

exit 0
"""


def run(cmd, **kwargs):
    return subprocess.run(cmd, check=True, **kwargs)


def require_root():
    if os.geteuid() != 0:
        raise SystemExit("image_patcher requires root (loop devices, mount)")


class LoopMount:
    """Gunzips image_path to a scratch copy, attaches it as a loop
    device with partitions, and mounts the ext4 root partition
    (partition 2, matching this project's factory image layout) rw.

    Not a context manager on purpose: repack() must run *between*
    unmounting the filesystem (so writes are flushed) and detaching
    the loop device, which doesn't fit __exit__'s single teardown
    point cleanly. Use the explicit open()/repack()/close() sequence,
    ideally wrapped in try/finally by the caller.
    """

    def __init__(self, image_path, root_partition=2):
        self.image_path = image_path
        self.root_partition = root_partition
        self.workdir = None
        self.raw_path = None
        self.loop_dev = None
        self.mount_point = None

    def open(self):
        self.workdir = tempfile.mkdtemp(prefix="omnb-")
        self.raw_path = os.path.join(self.workdir, "image.img")
        with gzip.open(self.image_path, "rb") as src, open(self.raw_path, "wb") as dst:
            shutil.copyfileobj(src, dst, length=4 * 1024 * 1024)

        out = run(["losetup", "--show", "-fP", self.raw_path], capture_output=True, text=True).stdout
        self.loop_dev = out.strip()

        self.mount_point = os.path.join(self.workdir, "root")
        os.makedirs(self.mount_point, exist_ok=True)
        run(["mount", "-o", "rw", f"{self.loop_dev}p{self.root_partition}", self.mount_point])
        return self.mount_point

    def repack(self, output_path):
        """Unmounts (flushing writes) and re-gzips the modified raw
        image to output_path. The loop device stays attached - call
        close() afterward regardless of whether this succeeds."""
        run(["sync"])
        run(["umount", self.mount_point])
        self.mount_point = None
        with open(self.raw_path, "rb") as src, gzip.open(output_path, "wb", compresslevel=6) as dst:
            shutil.copyfileobj(src, dst, length=4 * 1024 * 1024)

    def close(self):
        if self.mount_point:
            subprocess.run(["umount", self.mount_point], check=False)
            self.mount_point = None
        if self.loop_dev:
            subprocess.run(["losetup", "-d", self.loop_dev], check=False)
            self.loop_dev = None
        if self.workdir:
            shutil.rmtree(self.workdir, ignore_errors=True)
            self.workdir = None


def bake_image(base_image_path, output_image_path, config_files, admin_password, progress=None):
    """Loop-mounts base_image_path, writes config_files (dict of
    filename -> content, from uci_config.generate_all) into a template
    dir plus a uci-defaults script that installs them at first boot,
    then repacks to output_image_path. Does not modify base_image_path.

    progress, if given, is called with short status strings so a
    curses UI can show what's happening (this can take tens of seconds
    - the image is 60+MB and gunzip/gzip dominate the time)."""
    require_root()

    def report(msg):
        if progress:
            progress(msg)

    report("unpacking base image...")
    lm = LoopMount(base_image_path)
    try:
        root = lm.open()

        template_dir = os.path.join(root, TEMPLATE_DIR.lstrip("/"))
        os.makedirs(template_dir, exist_ok=True)

        report("writing node config...")
        for name, content in config_files.items():
            with open(os.path.join(template_dir, name), "w") as f:
                f.write(content)

        uci_defaults_dir = os.path.join(root, "etc", "uci-defaults")
        os.makedirs(uci_defaults_dir, exist_ok=True)
        script_path = os.path.join(uci_defaults_dir, UCI_DEFAULTS_NAME)
        with open(script_path, "w") as f:
            f.write(UCI_DEFAULTS_SCRIPT.replace("__ADMIN_PASSWORD__", admin_password))
        os.chmod(script_path, 0o755)

        report("repacking image (this takes a while)...")
        lm.repack(output_image_path)
        report("done")
    finally:
        lm.close()
